### ISSUE TITLE
Entering nether on multiplayer gives internal Server error and crashes server

### ISSUE THREAD

**Issue by Ingemaru** [Majrusz/MajruszsProgressiveDifficultyMod#2]
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.DimensionType.func_242725_p()Lnet/minecraft/util/ResourceLocation;
	at com.majruszs_difficulty.events.IncreaseGameDifficulty.enableExpertMode(IncreaseGameDifficulty.java:22) ~[majruszs_difficulty:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_220_IncreaseGameDifficulty_enableExpertMode_PlayerChangedDimensionEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerChangedDimensionEvent(BasicEventHooks.java:39) ~[forge:?]
	at net.minecraft.entity.player.ServerPlayerEntity.changeDimension(ServerPlayerEntity.java:679) ~[?:?]
	at net.minecraft.entity.Entity.func_241206_a_(Entity.java:2120) ~[?:?]
	at net.minecraft.entity.Entity.func_213284_aV(Entity.java:1779) ~[?:?]
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:403) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70030_z(LivingEntity.java:295) ~[?:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:387) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2113) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
	... 9 more
[31Dez2020 01:12:14.251] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Kiriniko lost connection: Internal server error
[31Dez2020 01:12:14.252] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [pogchamp] Kiriniko left the game
[31Dez2020 01:12:14.659] [Server thread/WARN] [net.minecraft.world.server.ServerWorld/]: Trying to add entity with duplicated UUID 11ccc35a-d161-4733-88a1-07790a34f7fc. Existing minecraft:chest_minecart#234, new: minecraft:chest_minecart#349
[31Dez2020 01:13:36.209] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Stopping the server

**Comment by Majrusz** [comment]
Thanks for reporting this! In the latest update this is fixed. The problem is that I wrote this modification for Minecraft version 1.16.3, and in the next version (1.16.4) some functions changed their name.
