### ISSUE TITLE
Crash when fighting with undead army

### ISSUE THREAD

**Issue by mocksonline** [Majrusz/MajruszsProgressiveDifficultyMod#202]
Crash when fighting with undead army, half undead army killed.
partial log:
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_6092(net.minecraft.class_1293)" because "entity" is null
	at com.majruszsdifficulty.undeadarmy.UndeadArmy.lambda$highlight$31(UndeadArmy.java:103)
	at com.majruszsdifficulty.undeadarmy.UndeadArmy.lambda$forEachSpawnedUndead$35(UndeadArmy.java:147)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.majruszsdifficulty.undeadarmy.UndeadArmy.forEachSpawnedUndead(UndeadArmy.java:147)
	at com.majruszsdifficulty.undeadarmy.UndeadArmy.highlight(UndeadArmy.java:103)
	at com.majruszsdifficulty.undeadarmy.listeners.MobHighlighter.highlight(MobHighlighter.java:17)
	at com.majruszlibrary.events.base.Event.accept(Event.java:49)
	at com.majruszlibrary.events.base.Events.accept(Events.java:61)
	at com.majruszlibrary.events.base.Events.dispatch(Events.java:20)
	at com.majruszsdifficulty.undeadarmy.UndeadArmy.tick(UndeadArmy.java:99)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.majruszsdifficulty.undeadarmy.UndeadArmyHelper.tick(UndeadArmyHelper.java:90)
	at com.majruszlibrary.events.base.Event.accept(Event.java:49)
	at com.majruszlibrary.events.base.Events.accept(Events.java:61)
	at com.majruszlibrary.events.base.Events.dispatch(Events.java:20)
	at net.minecraft.server.MinecraftServer.handler$dle000$majruszlibrary$tickServer(MinecraftServer.java:14324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.handler$bdl000$carpet$modifiedRunLoop(MinecraftServer.java:19442)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
(This is the only warning message, I think it's enough)
If need more details, please tell me

**Comment by Majrusz** [comment]
Hello, it got fixed with the latest 1.9.5 version, have you tried it?
