### ISSUE TITLE
1.20.1-forge-1.9.6:Cannot get property DirectionProperty

### ISSUE THREAD

**Issue by JackZhangCNCC** [Majrusz/MajruszsProgressiveDifficultyMod#207]
Time: 2024-01-23 05:00:20
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:deepslate}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23964!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at com.majruszsdifficulty.entity.CursedArmor.getSpawnPosition(CursedArmor.java:295) ~[%5BMajrusz的进阶难度%5D%20majruszs-difficulty-forge-1.20.1-1.9.6.jar%23582!/:1.9.6] {re:classloading}
	at com.majruszsdifficulty.entity.CursedArmor.lambda$spawnCursedArmor$33(CursedArmor.java:256) ~[%5BMajrusz的进阶难度%5D%20majruszs-difficulty-forge-1.20.1-1.9.6.jar%23582!/:1.9.6] {re:classloading}
	at com.majruszlibrary.time.delays.Delay.finish(Delay.java:21) ~[majrusz-library-forge-1.20.1-7.0.3.jar%23887!/:7.0.3] {re:classloading}
	at com.majruszlibrary.time.TimeHelper.lambda$update$5(TimeHelper.java:109) ~[majrusz-library-forge-1.20.1-7.0.3.jar%23887!/:7.0.3] {re:classloading,re:mixin}
	at com.majruszlibrary.platform.LogicalSafe.run(LogicalSafe.java:45) ~[majrusz-library-forge-1.20.1-7.0.3.jar%23887!/:7.0.3] {re:classloading}
	at com.majruszlibrary.time.TimeHelper.update(TimeHelper.java:103) ~[majrusz-library-forge-1.20.1-7.0.3.jar%23887!/:7.0.3] {re:classloading,re:mixin}
	at com.majruszlibrary.time.TimeHelper.lambda$static$1(TimeHelper.java:31) ~[majrusz-library-forge-1.20.1-7.0.3.jar%23887!/:7.0.3] {re:classloading,re:mixin}
	at com.majruszlibrary.events.base.Event.accept(Event.java:49) ~[majrusz-library-forge-1.20.1-7.0.3.jar%23887!/:7.0.3] {re:classloading}
	at com.majruszlibrary.events.base.Events.accept(Events.java:61) ~[majrusz-library-forge-1.20.1-7.0.3.jar%23887!/:7.0.3] {re:mixin,re:classloading}
	at com.majruszlibrary.events.base.Events.dispatch(Events.java:20) ~[majrusz-library-forge-1.20.1-7.0.3.jar%23887!/:7.0.3] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.handler$dhd000$tickServer(MinecraftServer.java:5357) ~[client-1.20.1-20230612.114412-srg.jar%23964!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23964!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23964!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23964!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23964!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

**Comment by Aabaddon** [comment]
Smoothboot doesnt seem to be compatible with this mod

re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by Majrusz** [comment]
Hello, thanks for the report, I fixed it with the latest 1.9.7 release
