### ISSUE TITLE
Crash when crafting two accessories with AE2 Terminal / Minecraft 1.20.1 / forge : 47.2.0

### ISSUE THREAD

**Issue by IXOlex** [Majrusz/MajruszsProgressiveDifficultyMod#214]
Hello, the game crashes when I try to merge two accessories with AE2 crafting terminal but when i do it manually it's work fine 

Time: 2024-02-28 16:26:37
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because "this.data.extraBonus" is null
	at com.majruszsaccessories.common.AccessoryHolder.getExtraBonus(AccessoryHolder.java:181) ~[majruszs-accessories-forge-1.20.1-1.5.1.jar%23598!/:1.5.1] {re:mixin,re:classloading}
	at com.majruszsaccessories.common.AccessoryHolder.getBonus(AccessoryHolder.java:173) ~[majruszs-accessories-forge-1.20.1-1.5.1.jar%23598!/:1.5.1] {re:mixin,re:classloading}
	at com.majruszsaccessories.common.AccessoryHolder.getRarity(AccessoryHolder.java:217) ~[majruszs-accessories-forge-1.20.1-1.5.1.jar%23598!/:1.5.1] {re:mixin,re:classloading}
	at com.majruszsaccessories.items.AccessoryItem.m_41460_(AccessoryItem.java:40) ~[majruszs-accessories-forge-1.20.1-1.5.1.jar%23598!/:1.5.1] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41791_(ItemStack.java:809) ~[client-1.20.1-20230612.114412-srg.jar%23702!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:recipeessentials.mixins.json:nbt.ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:attributeslib.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:insanelib.mixins.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:majruszsaccessories-common.mixins.json:MixinItemStack,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:616) ~[client-1.20.1-20230612.114412-srg.jar%23702!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:recipeessentials.mixins.json:nbt.ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:attributeslib.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:insanelib.mixins.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:majruszsaccessories-common.mixins.json:MixinItemStack,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.client.gui.screens.Screen.m_280152_(Screen.java:246) ~[client-1.20.1-20230612.114412-srg.jar%23702!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin,pl:mixin:APP:nerb-common.mixins.json:ScreenMixin,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:werewolves.mixins.json:client.ScreenMixin,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:ae2.mixins.json:WrappedGenericStackTooltipModIdMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280553_(AbstractContainerScreen.java:169) ~[client-1.20.1-20230612.114412-srg.jar%23702!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:botania_xplat.mixins.json:client.AbstractContainerScreenAccessor,pl:mixin:APP:highlighter.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:attributeslib.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:APP:majruszlibrary-forge.mixins.json:MixinAbstractContainerScreen,pl:mixin:APP:ae2.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:ae2.mixins.json:ResizableSlotHighlightMixin,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:mixins.ipnext.json:MixinAbstractContainerScreen,pl:mixin:APP:inventoryessentials.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:mixins.epp.json:MixinAbstractContainerScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280072_(AbstractContainerScreen.java:163) ~[client-1.20.1-20230612.114412-srg.jar%23702!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:botania_xplat.mixins.json:client.AbstractContainerScreenAccessor,pl:mixin:APP:highlighter.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:attributeslib.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:APP:majruszlibrary-forge.mixins.json:MixinAbstractContainerScreen,pl:mixin:APP:ae2.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:ae2.mixins.json:ResizableSlotHighlightMixin,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:mixins.ipnext.json:MixinAbstractContainerScreen,pl:mixin:APP:inventoryessentials.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:mixins.epp.json:MixinAbstractContainerScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at appeng.client.gui.me.common.MEStorageScreen.m_280072_(MEStorageScreen.java:639) ~[appliedenergistics2-forge-15.0.21.jar%23456!/:15.0.21] {re:classloading}
	at appeng.client.gui.AEBaseScreen.renderTooltips(AEBaseScreen.java:313) ~[appliedenergistics2-forge-15.0.21.jar%23456!/:15.0.21] {re:mixin,re:classloading}
	at appeng.client.gui.AEBaseScreen.m_88315_(AEBaseScreen.java:244) ~[appliedenergistics2-forge-15.0.21.jar%23456!/:15.0.21] {re:mixin,re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23702!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin,pl:mixin:APP:nerb-common.mixins.json:ScreenMixin,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:werewolves.mixins.json:client.ScreenMixin,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:ae2.mixins.json:WrappedGenericStackTooltipModIdMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.0-universal.jar%23707!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.0-universal.jar%23707!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23702!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23702!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.MinecraftAccessor,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:vampirism.mixins.json:client.MinecraftMixin,pl:mixin:APP:embeddiumplus.mixin.json:fps.GpuUsageMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23702!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.MinecraftAccessor,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:vampirism.mixins.json:client.MinecraftMixin,pl:mixin:APP:embeddiumplus.mixin.json:fps.GpuUsageMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.0.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by Majrusz** [comment]
Hello, this is related to accessories mod not the difficulty one. Anyway, thanks for the report, I will investigate it further
