### ISSUE TITLE
Crashes when Undead Army Spawns in

### ISSUE THREAD

**Issue by PrussianFungus** [Majrusz/MajruszsProgressiveDifficultyMod#23]
On my singleplayer world, 1.16.4, when an undead army spawns in, no matter where I am it'll crash the game. Specifically, when the bar fills up.

While I am here, would it at all be possible to add a config to disable raids? Thanks in advance.

```
java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.particles.ItemParticleData.<init>(ItemParticleData.java:40) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.EntityType.handler$zgb000$spawnFromItemStack(EntityType.java:640) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabrication.mixins.json:c_tweaks.cracking_spawn_eggs.MixinEntityType,pl:mixin:A}
	at net.minecraft.entity.EntityType.func_220331_a(EntityType.java:313) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabrication.mixins.json:c_tweaks.cracking_spawn_eggs.MixinEntityType,pl:mixin:A}
	at com.majruszs_difficulty.events.UndeadArmy.spawnWaveEnemies(UndeadArmy.java:288) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.UndeadArmy.nextWave(UndeadArmy.java:234) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.UndeadArmy.tickBetweenWaves(UndeadArmy.java:191) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.UndeadArmy.tick(UndeadArmy.java:153) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.undead_army.UndeadArmyManager.tickArmies(UndeadArmyManager.java:150) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.undead_army.UndeadArmyManager.tick(UndeadArmyManager.java:92) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.undead_army.UndeadArmyManager.onUpdate(UndeadArmyManager.java:129) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_446_UndeadArmyManager_onUpdate_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:115) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$16039/1165951546.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
```

**Comment by Majrusz** [comment]
Do you have any other mods? And what version of Forge are you using?

**Comment by PrussianFungus** [comment]
I am running forge 35.1.28. Yes, I do have other mods, however the ones I've run with typically have no problems with your mod at all. I'll check and see if any of the recent additions are causing this. Also, if it helps, I'm on version 1.16.4-0.3.1 of your mod while running optifine (Though without it the crash still occurs).
Logging on afterwards does end the wave of mobs, but then continues the next wave until I crash. This keeps on happening until the world works through all of the waves.

**Comment by Majrusz** [comment]
Could you download the latest version 0.4.1 and see if the problem still occurs?

**Comment by PrussianFungus** [comment]
Sadly it seems like it's the same problem. Bar loads up, once it gets full, crashes as per usual.
`java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.particles.ItemParticleData.<init>(ItemParticleData.java:40) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.EntityType.handler$zgb000$spawnFromItemStack(EntityType.java:640) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabrication.mixins.json:c_tweaks.cracking_spawn_eggs.MixinEntityType,pl:mixin:A}
	at net.minecraft.entity.EntityType.func_220331_a(EntityType.java:313) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabrication.mixins.json:c_tweaks.cracking_spawn_eggs.MixinEntityType,pl:mixin:A}
	at com.majruszs_difficulty.events.UndeadArmy.spawnWaveEnemies(UndeadArmy.java:294) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.UndeadArmy.nextWave(UndeadArmy.java:238) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.UndeadArmy.tickBetweenWaves(UndeadArmy.java:195) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.UndeadArmy.tick(UndeadArmy.java:157) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.undead_army.UndeadArmyManager.tickArmies(UndeadArmyManager.java:152) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.undead_army.UndeadArmyManager.tick(UndeadArmyManager.java:94) ~[?:1.0] {re:classloading}
	at com.majruszs_difficulty.events.undead_army.UndeadArmyManager.onUpdate(UndeadArmyManager.java:131) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_503_UndeadArmyManager_onUpdate_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:115) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$16158/1137199912.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}`

**Comment by PrussianFungus** [comment]
There's also only three mods I could see it conflicting with as they were added when I was experiencing these crashes.
EffectEnchantments, Forgery, and Evolved RPG. I'll see if I can narrow it down further and I'll let you know.

**Comment by PrussianFungus** [comment]
Got it, it's Forgery that's causing the crash. The wave loaded in just fine without it, but I wouldn't see why. Scrolling through the config shows nothing that'd effect spawners or even mobs. 
Downloaded the most recent version of both mods, but the crash still occurs.

**Comment by OhHeyItsK** [comment]
The Undead Army is crashing me too, like 90% of the times I beat it, and I don't have any of those mods. I'm not even getting a crash report. Everything just freezes. Well, everything ELSE freezes. I can walk around, but I can't interact with any mobs or blocks. Mobs stop moving, can't change the difficulty. 100% locked, and then I have to force close it.

**Comment by PrussianFungus** [comment]
I've only gotten deadlocks with world generation mods rather than mobs. That's certainly strange to say the least, but I'd say that's related to a different mod and is a different crash as a whole. Either way, good luck with finding out what's causing it.

**Comment by wallxnr** [comment]
The same thing is happening to me too, just start a new wave that the game crashes, at first I thought it was because of the shaders I use (BSL), but it wasn't, I tested it with the mod individually and without any shader, but it also occurred this, Forge version 35.1.36 and mod version 0.4.1

![Screenshot (206)](https://user-images.githubusercontent.com/78543502/107117446-3675cd00-6859-11eb-8ca1-6d0fa04e2d62.png)

**Comment by Majrusz** [comment]
Thank you all! I have finally found what was causing the crash and in the next update this should no longer be an issue!
