### ISSUE TITLE
Server crash with forge 1.16.5 36.00.13

### ISSUE THREAD

**Issue by smith0358** [Majrusz/MajruszsProgressiveDifficultyMod#32]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/28/21 11:17 PM
Description: Ticking entity

java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_272] {}
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) ~[?:1.8.0_272] {}
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:336) ~[performant:1.16.2-4-3.30m] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.AbstractSkeletonEntity.func_70636_d(AbstractSkeletonEntity.java:116) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:bows.5,xf:fml:forge:bows.4}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_272] {}
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) ~[?:1.8.0_272] {}
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:336) ~[performant:1.16.2-4-3.30m] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.AbstractSkeletonEntity.func_70636_d(AbstractSkeletonEntity.java:116) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:bows.5,xf:fml:forge:bows.4}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: majruszs_difficulty:elite_skeleton (com.majruszs_difficulty.entities.EliteSkeletonEntity)
	Entity ID: 78307
	Entity Name: Elite Skeleton
	Entity's Exact location: -609.13, 49.00, 238.85
	Entity's Block location: World: (-610,49,238), Chunk: (at 14,3,14 in -39,14; contains blocks -624,0,224 to -609,255,239), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Entity's Momentum: -0.36, 0.32, -0.17
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 5 total; [ServerPlayerEntity['OuOsonyOuO'/1342, l='ServerLevel[KumakumacyanWorld]', x=11988.70, y=63.00, z=1505.16], ServerPlayerEntity['killCow1012'/3791, l='ServerLevel[KumakumacyanWorld]', x=-608.22, y=49.00, z=239.29], ServerPlayerEntity['flandersLLBBA'/56151, l='ServerLevel[KumakumacyanWorld]', x=-559.77, y=84.30, z=201.78], ServerPlayerEntity['nekomiyatomoka'/19264, l='ServerLevel[KumakumacyanWorld]', x=-492.02, y=119.06, z=18.66], ServerPlayerEntity['eric31318'/67561, l='ServerLevel[KumakumacyanWorld]', x=-407.66, y=188.00, z=506.05]]
	Chunk stats: ServerChunkCache: 6098
	Level dimension: minecraft:overworld
	Level spawn location: World: (-383,65,181), Chunk: (at 1,4,5 in -24,11; contains blocks -384,0,176 to -369,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 132153134 game time, 187827101 day time
	Level name: KumakumacyanWorld
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.18.0-240.1.1.el8_3.x86_64
	Java Version: 1.8.0_272, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc.
	Memory: 1139059400 bytes (1086 MB) / 3201892352 bytes (3053 MB) up to 5349376000 bytes (5101 MB)
	CPUs: 6
	JVM Flags: 17 total; -Xmx5G -Xms3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -Xincgc -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=500 -XX:SurvivorRatio=16 -XX:TargetSurvivorRatio=90 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -Xnoclassgc -XX:LargePageSizeInBytes=2m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/Kumakumacyan.jar object_holder_definalize PLUGINSERVICE 
		/Kumakumacyan.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/Kumakumacyan.jar capability_inject_definalize PLUGINSERVICE 
		/Kumakumacyan.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/Kumakumacyan.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.13
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		mining-helmet-1.16.4-2.0.0-tw.jar                 |Mining Helmet                 |mining_helmet                 |2.0.0               |DONE      |NOSIGNATURE
		Bountiful+Baubles+FORGE-1.16.3-0.0.2.jar          |Bountiful Baubles             |bountifulbaubles              |NONE                |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.71-tw.jar                        |Just Enough Items             |jei                           |7.6.1.71            |DONE      |NOSIGNATURE
		DoggyTalents-1.16.4-2.0.1.3.jar                   |Doggy Talents 2               |doggytalents                  |2.0.1.3             |DONE      |NOSIGNATURE
		caelus-forge-1.16.5-2.1.2.2.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.2.2      |DONE      |NOSIGNATURE
		wonderful-enchantments-1.16.4-1.1.1.jar           |Wonderful Enchantments        |wonderful_enchantments        |1.1.1               |DONE      |NOSIGNATURE
		reap-1.16.5-1.0.0.jar                             |Reap Mod                      |reap                          |1.16.5-1.0.0        |DONE      |NOSIGNATURE
		colytra-forge-1.16.4-5.1.0.0.jar                  |Colytra                       |colytra                       |1.16.4-5.1.0.0      |DONE      |NOSIGNATURE
		RingsOfAscension-1.16.3-1.5.6.jar                 |Rings of Ascension            |ringsofascension              |1.5.6               |DONE      |NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |DONE      |NOSIGNATURE
		XaerosWorldMap_1.12.0.2_Forge_1.16.5-tw.jar       |Xaero's World Map             |xaeroworldmap                 |1.12.0              |DONE      |NOSIGNATURE
		Controlling-7.0.0.13-1.16.5-tw.jar                |Controlling                   |controlling                   |7.0.0.13            |DONE      |NOSIGNATURE
		curioofundying-forge-1.16.4-5.1.0.0.jar           |Curio of Undying              |curioofundying                |1.16.4-5.1.0.0      |DONE      |NOSIGNATURE
		Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |DONE      |92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		simpleplanes-1.16.4-4.0.8.jar                     |Simple Planes                 |simpleplanes                  |1.16.4-4.0.8        |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2-tw.jar             |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.13-universal.jar                |Forge                         |forge                         |36.0.13             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		scuba-gear-1.16.5-1.0.2.jar                       |Scuba Gear                    |scuba_gear                    |1.0.2               |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.13-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.2-tw.jar       |EnchantmentDescriptions       |enchdesc                      |7.0.2               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.431-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.431   |DONE      |NOSIGNATURE
		ironfurnaces-1.16.5-2.6.4-tw.jar                  |Iron Furnaces                 |ironfurnaces                  |2.6.4               |DONE      |NOSIGNATURE
		forbidden_arcanus-1.16.3-1.0.2-tw.jar             |Forbidden & Arcanus           |forbidden_arcanus             |1.16.3-1.0.2        |DONE      |NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.0.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.0        |DONE      |NOSIGNATURE
		simplefarming-1.16.4-1.3.5.jar                    |Simple Farming                |simplefarming                 |1.16.4-1.3.5        |DONE      |NOSIGNATURE
		fairylights-4.0.5-1.16.5.jar                      |Fairy Lights                  |fairylights                   |4.0.5               |DONE      |NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.1.jar                     |Spawner Fix                   |sf                            |1.0.0.1             |DONE      |NOSIGNATURE
		simplybackpacks-1.16.3-1.4.13.jar                 |Simply Backpacks              |simplybackpacks               |1.16.3-1.4.13       |DONE      |NOSIGNATURE
		majrusz-library-1.16.4-1.4.0.jar                  |Majrusz Library               |majrusz_library               |1.4.0               |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.4.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.4.0      |DONE      |NOSIGNATURE
		SpartanShields-1.16.4-2.1.1.jar                   |Spartan Shields               |spartanshields                |2.1.1               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-50-tw.jar                        |Patchouli                     |patchouli                     |1.16.4-50           |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.4.0_Forge_1.16.5-tw.jar         |Xaero's Minimap               |xaerominimap                  |21.4.0              |DONE      |NOSIGNATURE
		gravestone-1.16.5-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.1        |DONE      |NOSIGNATURE
		extlights-3.3.jar                                 |Extended Lights               |extlights                     |3.3                 |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2-tw.jar                |Storage Drawers               |storagedrawers                |8.2.2               |DONE      |NOSIGNATURE
		sit-1.16.2-v1.3.jar                               |Sit                           |sit                           |v1.3                |DONE      |NOSIGNATURE
		performant-1.16.2-4-3.30m.jar                     |Performant                    |performant                    |3.30m               |DONE      |NOSIGNATURE
		angelring-1.16.3-1.3.3.jar                        |Angel Ring                    |angelring                     |1.3.3               |DONE      |NOSIGNATURE
		backpacked-1.7.1-1.16.3.jar                       |Backpacked                    |backpacked                    |1.7.1               |DONE      |NOSIGNATURE
		backpacker-1.2.1-1.16.3.jar                       |Backpacker                    |backpacker                    |1.2.1               |DONE      |NOSIGNATURE
		InventoryHud_[1.16.2-1.16.5].forge-3.2.1.jar      |Inventory HUD+(Forge edition) |inventoryhud                  |3.2.1               |DONE      |NOSIGNATURE
		Gobber2-Forge-1.16.5-2.3.48.jar                   |Gobber 2                      |gobber2                       |2.3.48              |DONE      |NOSIGNATURE
		miraisoftloginmessages-1.16.2-1.16.5-1.0.2b.jar   |Custom login messages         |miraisoftloginmessages        |1.0.2b              |DONE      |NOSIGNATURE
		majruszs-difficulty-1.16.4-0.5.1.jar              |Majrusz's Progressive Difficul|majruszs_difficulty           |0.5.1               |DONE      |NOSIGNATURE
		architectury-1.8.128-forge.jar                    |Architectury                  |architectury                  |1.8.128             |DONE      |NOSIGNATURE
		ftb-gui-library-1605.2.1.39-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.39         |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |DONE      |NOSIGNATURE
		Aquaculture-1.16.5-2.1.15.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.15       |DONE      |NOSIGNATURE
		switchbow-1.7.jar                                 |Switch-Bow                    |switchbow                     |1.7                 |DONE      |NOSIGNATURE
		valhelsia_core-16.0.5.jar                         |Valhelsia Core                |valhelsia_core                |16.0.5              |DONE      |NOSIGNATURE
		GameMenuModOption-1.16.4-1.4.jar                  |Game Menu Mod Option          |gamemenumodoption             |1.4                 |DONE      |NOSIGNATURE
		supertools-1.16.5-4.1.jar                         |Vanilla+ Tools                |supertools                    |version             |DONE      |NOSIGNATURE
	Crash Report UUID: aa927a20-a030-4993-9e74-20ce91681b05
	Player Count: 5 / 50; [ServerPlayerEntity['OuOsonyOuO'/1342, l='ServerLevel[KumakumacyanWorld]', x=11988.70, y=63.00, z=1505.16], ServerPlayerEntity['killCow1012'/3791, l='ServerLevel[KumakumacyanWorld]', x=-608.22, y=49.00, z=239.29], ServerPlayerEntity['nekomiyatomoka'/19264, l='ServerLevel[KumakumacyanWorld]', x=-492.02, y=119.06, z=18.66], ServerPlayerEntity['flandersLLBBA'/56151, l='ServerLevel[KumakumacyanWorld]', x=-559.77, y=84.30, z=201.78], ServerPlayerEntity['eric31318'/67561, l='ServerLevel[KumakumacyanWorld]', x=-407.66, y=188.00, z=506.05]]
	Data Packs: vanilla, mod:biomesoplenty, mod:mining_helmet (incompatible), mod:ironfurnaces, mod:jei, mod:forbidden_arcanus (incompatible), mod:simplefarming, mod:fairylights, mod:simplybackpacks (incompatible), mod:wonderful_enchantments, mod:reap, mod:patchouli (incompatible), mod:waystones (incompatible), mod:gravestone, mod:xaeroworldmap, mod:controlling, mod:storagedrawers (incompatible), mod:backpacked (incompatible), mod:backpacker, mod:ftbguilibrary (incompatible), mod:inventoryhud, mod:simpleplanes (incompatible), mod:forge, mod:xaerominimap, mod:waila, mod:sf, mod:aquaculture (incompatible), mod:bookshelf, mod:caelus, mod:enchdesc, mod:randompatches, mod:supertools (incompatible), mod:appleskin, mod:swingthroughgrass (incompatible), mod:miraisoftloginmessages, mod:majrusz_library, mod:curios, mod:smoothboot, mod:spartanshields, mod:sit, mod:performant (incompatible), mod:angelring (incompatible), mod:architectury, mod:aiimprovements, mod:bountifulbaubles (incompatible), mod:doggytalents (incompatible), mod:ringsofascension (incompatible), mod:curioofundying, mod:scuba_gear (incompatible), mod:extlights, mod:gobber2, mod:switchbow, mod:gamemenumodoption, mod:majruszs_difficulty, mod:valhelsia_core, mod:colytra (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Majrusz** [comment]
This should work properly in the next update.
