### ISSUE TITLE
Error with bandage

### ISSUE THREAD

**Issue by Silivek** [Majrusz/MajruszsProgressiveDifficultyMod#97]
I got this error while hosting a server using this mod. I'm not sure what caused it but the issue seems to be from this mod.
Error found in Server log:
`[13:43:24] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: class net.minecraft.world.item.AirItem cannot be cast to class com.majruszsdifficulty.items.BandageItem (net.minecraft.world.item.AirItem is in module minecraft@1.19 of loader 'TRANSFORMER' @7ed49a7f; com.majruszsdifficulty.items.BandageItem is in module majruszsdifficulty@1.5.0 of loader 'TRANSFORMER' @7ed49a7f)
	Index: 4
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon eventPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
		2: NORMAL
		3: ASM: class com.teamremastered.endrem.events.ModEvents onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
		4: ASM: class com.mlib.gamemodifiers.contexts.OnPlayerInteractContext onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
		5: ASM: de.castcrafter.travelanchors.EventListener@2c878cb4 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
		6: ASM: class com.hollingsworth.arsnouveau.common.camera.CameraEvents onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
		7: ASM: Block{minecraft:air} onPlayerRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
		8: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@48e276ed curioRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class com.majruszsdifficulty.items.BandageItem (net.minecraft.world.item.AirItem is in module minecraft@1.19 of loader 'TRANSFORMER' @7ed49a7f; com.majruszsdifficulty.items.BandageItem is in module majruszsdifficulty@1.5.0 of loader 'TRANSFORMER' @7ed49a7f)
	at TRANSFORMER/majruszsdifficulty@1.5.0/com.majruszsdifficulty.items.BandageItem$BandageUse.removeBleeding(BandageItem.java:109)
	at TRANSFORMER/majruszsdifficulty@1.5.0/com.majruszsdifficulty.items.BandageItem$BandageUse.useBandage(BandageItem.java:84)
	at TRANSFORMER/majruszlib@2.8.0/com.mlib.gamemodifiers.Context.lambda$handleContexts$0(Context.java:21)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/majruszlib@2.8.0/com.mlib.gamemodifiers.Context.handleContexts(Context.java:19)
	at TRANSFORMER/majruszlib@2.8.0/com.mlib.gamemodifiers.contexts.OnPlayerInteractContext.onRightClickItem(OnPlayerInteractContext.java:37)
	at TRANSFORMER/majruszlib@2.8.0/com.mlib.gamemodifiers.contexts.__OnPlayerInteractContext_onRightClickItem_RightClickItem.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@41.0.63/net.minecraftforge.common.ForgeHooks.onItemRightClick(ForgeHooks.java:719)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:282)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1053)
	at TRANSFORMER/minecraft@1.19/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29)
	at TRANSFORMER/minecraft@1.19/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7)
	at TRANSFORMER/minecraft@1.19/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.19/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
	at TRANSFORMER/minecraft@1.19/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:158)
	at TRANSFORMER/minecraft@1.19/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740)
	at TRANSFORMER/minecraft@1.19/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245)
	at java.base/java.lang.Thread.run(Thread.java:833)

[13:43:24] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@2a3d7db2, suppressing error
java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class com.majruszsdifficulty.items.BandageItem (net.minecraft.world.item.AirItem is in module minecraft@1.19 of loader 'TRANSFORMER' @7ed49a7f; com.majruszsdifficulty.items.BandageItem is in module majruszsdifficulty@1.5.0 of loader 'TRANSFORMER' @7ed49a7f)
	at com.majruszsdifficulty.items.BandageItem$BandageUse.removeBleeding(BandageItem.java:109) ~[majruszs-difficulty-1.19-1.5.0.jar%23162!/:1.5.0]
	at com.majruszsdifficulty.items.BandageItem$BandageUse.useBandage(BandageItem.java:84) ~[majruszs-difficulty-1.19-1.5.0.jar%23162!/:1.5.0]
	at com.mlib.gamemodifiers.Context.lambda$handleContexts$0(Context.java:21) ~[majrusz-library-1.19-2.8.0.jar%23161!/:2.8.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.mlib.gamemodifiers.Context.handleContexts(Context.java:19) ~[majrusz-library-1.19-2.8.0.jar%23161!/:2.8.0]
	at com.mlib.gamemodifiers.contexts.OnPlayerInteractContext.onRightClickItem(OnPlayerInteractContext.java:37) ~[majrusz-library-1.19-2.8.0.jar%23161!/:2.8.0]
	at com.mlib.gamemodifiers.contexts.__OnPlayerInteractContext_onRightClickItem_RightClickItem.invoke(.dynamic) ~[majrusz-library-1.19-2.8.0.jar%23161!/:2.8.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%2350!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2350!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2350!/:?]
	at net.minecraftforge.common.ForgeHooks.onItemRightClick(ForgeHooks.java:719) ~[forge-1.19-41.0.63-universal.jar%23203!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:282) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1053) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:158) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245) ~[server-1.19-20220607.102129-srg.jar%23198!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
`
Any help with this would be appreciated.

**Comment by Majrusz** [comment]
Thanks for reporting that, fixed here 0d6915147122edee25189bdd065ee7ee7cdfbff7 and new update will be available soon
